services:
  frontend:
    image: mindflow-app
    container_name: mindflow_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=production
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "5173:80"
